[package]
name = "file-deduplicator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
rayon = "1.10"
dialoguer = "0.11"
indicatif = "0.17"